### ISSUE TITLE
generator fails to modify Application Controller correctly

### ISSUE THREAD

**Issue by DanielKehoe** [talkable/talkable-ruby#17]
The generator attempts to modify the Application Controller in the file *app/controllers/application_controller.rb*. However Rails 5 dropped the `protect_from_forgery` directive so the generator fails to add the 

```
  before_action :load_talkable_offer
```

that is required. Can modify the file *lib/talkable/generators/install_generator.rb* to correct this.

**Comment by zhuravel** [comment]
cc @vitalikdanchenko @antonpaisov

**Comment by zhuravel** [comment]
@DanielKehoe Thank you!

**Comment by antonpaisov** [comment]
Fixed in a new gem version 1.0.2
