### ISSUE TITLE
API call register_affiliate_member fails

### ISSUE THREAD

**Issue by DanielKehoe** [talkable/talkable-ruby#20]
The generator adds this code to the Application Controller *app/controllers/application_controller.rb*:
```
class ApplicationController < ActionController::Base
  before_action :load_talkable_offer

  protected

  def load_talkable_offer
    origin = Talkable.register_affiliate_member
    @offer ||= origin.offer if origin
  end
end
```

`Talkable.register_affiliate_member` fails with the error:
```
Talkable::API::BadRequest at /users/sign_in
Either email or visitor must be present.
```

**Comment by antonpaisov** [comment]
First of all, do we really want to put this code in the application controller during the generation process? IMO it would make more sense to tell developers to add this code to a controller that is relevant to them.

Second, this doesn't change the fact that it's not clear to me why we get this error here. Need to investigate.

cc @vitalikdanchenko

**Comment by DanielKehoe** [comment]
Putting the code in the Application Controller means putting the referral offer on every page. That's convenient for a quick demo (and the only controller the generator will be able to always find is the Application Controller). However, I think we're better off asking the developer to add the code manually to the controller that renders a page where they want to see an offer. We are going to ask them to manually add code anyway, for the Purchase Registration.

There's another option. We could make the generator smart enough to recognize the rails-stripe-coupon example application (with conditional generation that looks for a Visitors Controller). Then install the code automatically. Let's discuss this option.

**Comment by antonpaisov** [comment]
@DanielKehoe I think if there's a problem of integration with rails-stripe-coupon app, it will appear in other apps too. So I still want to make it work even if it's a part of application controller in this app.

But overall I also think that it's better to make this change as a manual one, not the one within the generator.
